name: Deploy worker to stage

on:
  push:
    branches: [main]
    paths:
      - "workers/canvas-share/**"
      - "daemon/client/**"
      - "daemon/build.ts"
      - ".github/workflows/deploy-worker.yml"
      - ".github/workflows/deploy-worker-stage.yml"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-worker.yml
    with:
      env: stage
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      SHARE_AUTH_TOKEN: ${{ secrets.SHARE_AUTH_TOKEN_STAGE }}
